import { useEffect, useState } from 'react'
import Head from 'next/head';
import { getLaunches } from '../services/launches/launchesService';
import LaunchGrid from '../components/LaunchGrid/LaunchGrid';
import styles from './index.module.css';

export default function Home() {
  const [launches, setLaunches] = useState(null);

  useEffect(() => {
    async function makeRequest() {
      setLaunches(await getLaunches());
    }

    makeRequest();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>SpaceX Launches</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          SpaceX Launches
        </h1>

        {!launches && <p className={styles.description}>No launches found</p>}
        {!!launches && <LaunchGrid launches={launches} />}
      </main>
    </div>
  );
}
